git:
    depth: 1
language: python
install:
    - pip install . codecov
script:
    - coverage run test
python:
    - "3.5"
    - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: nightly
      dist: xenial
      sudo: true
after_success:
    - codecov
