git:
    depth: 1
language: python
install:
    - pip install . codecov pytest-trio
script:
    - coverage run tests
matrix:
  include:
    - python: nightly
      dist: xenial
      sudo: true
after_success:
    - codecov
