git:
    depth: 1
language: python
install:
    - pip install . codecov
script:
    - coverage run tests
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
    - python: nightly
      dist: xenial
      sudo: true
after_success:
    - codecov
